### ISSUE TITLE
Populate profile page with email if email is given

### ISSUE THREAD

**Issue by unkrich** [monosidev/monosi#183]
## Description

Currently on application start, an email is collected to create a user for monosi. When navigating to the settings > profile page, there is a form for editing this email. 

It does not currently show the existing email or allow the user to update the email.

## Expected behavior

Expected behavior is that the user would be able to see the email they are using and update it here.

## Steps to reproduce

1. Start application
2. Go to Settings > Profile

## Potential Fix

1. Extract email form from GettingStarted into ProfileForm
https://github.com/monosidev/monosi/blob/master/src/ui/src/pages/app/onboarding/GettingStarted/index.tsx#L35-L49
https://github.com/monosidev/monosi/blob/master/src/ui/src/pages/settings/Profile/index.tsx#L53
https://github.com/monosidev/monosi/blob/master/src/ui/src/components/forms/ProfileForm/index.tsx

2. Add extra fetch on load to fill the form's value/placeholder with the existing email if exists.
e.g. 
```
  const [email, setEmail] = useState<string>('');
  useEffect(() => {
    async function loadEmail() {
      let res = await UserService.getAll();
      if (res !== null && res.user && res.user.email) {
        setEmail(res.user.email);
      }
    }

    loadEmail();
  }, []);
```

**Comment by GabeK0** [comment]
Self-assigning this issue
