### ISSUE TITLE
Generate FQTN in profiler if possible

### ISSUE THREAD

**Issue by iporollo** [monosidev/monosi#21]
## Description
When running the command `monosi profile`, the `table` string in each monitor is generated with an incorrect format. It currently creates just the table name. Instead, for Snowflake, it should generate `<database_name>.<schema_name>.<table_name>`

## Steps to reproduce
1. Setup a monosi project with a connected source
2. Run `monosi profile` in the monosi project directory
3. Navigate to a monitor in the generated `bootstrapped-monitors` folder
4. Notice that the monitor's `table` key only has the table name as the value. Instead, we should have `<database_name>.<schema_name>.<table_name>`

**Comment by unkrich** [comment]
It's not necessarily true that all of these qualifiers need to be on the table name, but it's also not bad practice to add them if we have them - commenting on the PR with more thoughts.

**Comment by unkrich** [comment]
I believe we are doing this now as it is currently a requirement to use the fqtn across the entire application.
