### ISSUE TITLE
Test database connection - CLI

### ISSUE THREAD

**Issue by iporollo** [monosidev/monosi#24]
## Description

There needs to be a command to test the connection to a database for ensuring that the setup was correct. 

## Other notes

This should be a CLI command e.g. `monosi test-connection` or `monosi ping`  or something similar.

**Comment by unkrich** [comment]
@annamarieweber Are you interested in continuing this or should I wrap it up? Thanks!

**Comment by unkrich** [comment]
Likely going to pick this up this weekend due to lack of response here
