### ISSUE TITLE
Send anomaly alerts to slack

### ISSUE THREAD

**Issue by iporollo** [monosidev/monosi#32]
## Problem
I need to be alerted in slack when monosi detects anomalies.  

## Solution
Set up monosi to take a slack connection for sending alerts and information.

## Requirements
Slack workspace exists and one can retrieve the webhook for it to send events to. 

## Additional Context
The easiest way here would be simply add a way for input of a slack webhook URL and then sending a payload to that URL.

**Comment by unkrich** [comment]
We are now sending slack alerts when running the server. Marking complete and closing.
