### ISSUE TITLE
Send monitoring results to data store table

### ISSUE THREAD

**Issue by iporollo** [monosidev/monosi#37]
## Problem
I want my monosi monitoring results to be sent to a table in a database for analysis, visualization, etc.

## Solution
Provide ability to pipe monosi monitor results to a database table.

## Requirements
Some sort of flag / indicator that I want to send results to my data store. 
Format of results in a way that can be save in a data store.

**Comment by unkrich** [comment]
I am working on completing this.

**Comment by unkrich** [comment]
This is happening
