### ISSUE TITLE
Please stop spamming!

### ISSUE THREAD

**Issue by yani-** [monosidev/monosi#40]
## Description

_Please provide a high-level description of what you were trying to accomplish and what went wrong._

## Expected behavior

_Please provide clear and concise description of what you expected to happen._

## Steps to reproduce

3. See error

## Additional context

_Please provide any additional contex of screenshots of the._

**Comment by iporollo** [comment]
Hey Yani, thanks for the comment and apologies that you feel that way about my outreach. It wasn't intended to spam, I was genuinely curious to get feedback from an industry expert like yourself. Fully noted, will not be reaching back out.
